/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SingleMultipleChange;

import javax.swing.JButton;
import main.Courses;
import main.Student;

/**
 *
 * @author Pc
 */
public class SingleChange extends javax.swing.JFrame {

    /**
     * Creates new form SingleChange
     */
    private Student student;
    private Courses courses;
    public SingleChange(Student student, Courses courses) {
        this.student = student;
        this.courses = courses;
        this.setLocationRelativeTo(null);
        initComponents2(this);
    }

    private void initComponents2(SingleChange singlechange) {
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new java.awt.Color(220, 172, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 350));
        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 20, 20));
        for (int i = 0; i < courses.getSize(); i++) {
            JButton button = new javax.swing.JButton(courses.getCourse(i).getName());
            button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlechange.dispose();
            }
        });
            jPanel1.add(button);
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Math102Button = new javax.swing.JButton();
        CS102Button = new javax.swing.JButton();
        Math132Button = new javax.swing.JButton();
        ENG102 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 172, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 350));
        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 20, 20));

        Math102Button.setText("MATH102");
        Math102Button.setMaximumSize(new java.awt.Dimension(20, 20));
        Math102Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Math102ButtonMouseClicked(evt);
            }
        });
        Math102Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Math102ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Math102Button);

        CS102Button.setText("CS102");
        jPanel1.add(CS102Button);

        Math132Button.setText("MATH132");
        Math132Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Math132ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Math132Button);

        ENG102.setText("ENG102");
        jPanel1.add(ENG102);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);

        jButton3.setText("jButton3");
        jPanel1.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Math132ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Math132ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Math132ButtonActionPerformed

    private void Math102ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Math102ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Math102ButtonActionPerformed

    private void Math102ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Math102ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Math102ButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CS102Button;
    private javax.swing.JButton ENG102;
    private javax.swing.JButton Math102Button;
    private javax.swing.JButton Math132Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
