/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SectionChange;

import Forum.Forum;
import SchedulePage.SchedulePage;
import SingleMultipleChange.MultipleChange;
import SingleMultipleChange.SingleChange;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JButton;
import schedulepage.*;
import javax.swing.JFrame;
import main.Courses;
import main.Student;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author cagri
 */
public class SectionChangePage extends javax.swing.JFrame {

    private Student student;
    private Courses courses;
    public SectionChangePage(Student student, Courses courses) {
        this.courses = courses;
        this.setSize(1280,720);
        this.setLocationRelativeTo(null);
        this.student = student;
        initComponents();
        
    }
    public void close(){
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jButtonSectionChange = new javax.swing.JButton();
        jButtonForum = new javax.swing.JButton();
        jLabelClose = new javax.swing.JLabel();
        jButtonMultiChange = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        jLabelMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 172, 146));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(220, 172, 146));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(173, 112, 96));
        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 112, 96));
        jLabel1.setText("Current Schedule");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, -20, 440, 100);

        jPanel2.setBackground(new java.awt.Color(220, 172, 146));
        jPanel2.setLayout(new java.awt.GridLayout(10, 6, 20, 20));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(173, 112, 96));
        jTextField20.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(220, 172, 146));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("Hours");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField20);

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(173, 112, 96));
        jTextField18.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(220, 172, 146));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("Mon");
        jPanel2.add(jTextField18);

        jTextField30.setEditable(false);
        jTextField30.setBackground(new java.awt.Color(173, 112, 96));
        jTextField30.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField30.setForeground(new java.awt.Color(220, 172, 146));
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText("Tue");
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField30);

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(173, 112, 96));
        jTextField32.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField32.setForeground(new java.awt.Color(220, 172, 146));
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText("Wed");
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField32);

        jTextField33.setEditable(false);
        jTextField33.setBackground(new java.awt.Color(173, 112, 96));
        jTextField33.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField33.setForeground(new java.awt.Color(220, 172, 146));
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("Thurs");
        jPanel2.add(jTextField33);

        jTextField34.setEditable(false);
        jTextField34.setBackground(new java.awt.Color(173, 112, 96));
        jTextField34.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField34.setForeground(new java.awt.Color(220, 172, 146));
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("Fri");
        jPanel2.add(jTextField34);

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(173, 112, 96));
        jTextField21.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(220, 172, 146));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("8.30-9.20");
        jPanel2.add(jTextField21);

        jTextField35.setEditable(false);
        jTextField35.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText(student.getCourseAt(1,1));
        jPanel2.add(jTextField35);

        jTextField36.setEditable(false);
        jTextField36.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setText(student.getCourseAt(1,2));
        jPanel2.add(jTextField36);

        jTextField56.setEditable(false);
        jTextField56.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField56.setText(student.getCourseAt(1,3));
        jTextField56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField56ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField56);

        jTextField37.setEditable(false);
        jTextField37.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setText(student.getCourseAt(1,4));
        jPanel2.add(jTextField37);

        jTextField42.setEditable(false);
        jTextField42.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField42.setText(student.getCourseAt(1,5));
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField42);

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(173, 112, 96));
        jTextField22.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(220, 172, 146));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("9.30-10.20");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField22);

        jTextField43.setEditable(false);
        jTextField43.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField43.setText(student.getCourseAt(2,1));
        jPanel2.add(jTextField43);

        jTextField45.setEditable(false);
        jTextField45.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField45.setText(student.getCourseAt(2,2));
        jPanel2.add(jTextField45);

        jTextField46.setEditable(false);
        jTextField46.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setText(student.getCourseAt(2,3));
        jPanel2.add(jTextField46);

        jTextField47.setEditable(false);
        jTextField47.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setText(student.getCourseAt(2,4));
        jPanel2.add(jTextField47);

        jTextField48.setEditable(false);
        jTextField48.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField48.setText(student.getCourseAt(2,5));
        jPanel2.add(jTextField48);

        jTextField38.setEditable(false);
        jTextField38.setBackground(new java.awt.Color(173, 112, 96));
        jTextField38.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField38.setForeground(new java.awt.Color(220, 172, 146));
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("10.30-11.20");
        jTextField38.setToolTipText("");
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField38);

        jTextField49.setEditable(false);
        jTextField49.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField49.setText(student.getCourseAt(3,1));
        jPanel2.add(jTextField49);

        jTextField51.setEditable(false);
        jTextField51.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField51.setText(student.getCourseAt(3,2));
        jPanel2.add(jTextField51);

        jTextField52.setEditable(false);
        jTextField52.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField52.setText(student.getCourseAt(3,3));
        jPanel2.add(jTextField52);

        jTextField53.setEditable(false);
        jTextField53.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField53.setText(student.getCourseAt(3,4));
        jPanel2.add(jTextField53);

        jTextField54.setEditable(false);
        jTextField54.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField54.setText(student.getCourseAt(3,5));
        jPanel2.add(jTextField54);

        jTextField39.setEditable(false);
        jTextField39.setBackground(new java.awt.Color(173, 112, 96));
        jTextField39.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField39.setForeground(new java.awt.Color(220, 172, 146));
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("11.30-12.20");
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField39);

        jTextField55.setEditable(false);
        jTextField55.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField55.setText(student.getCourseAt(4,1));
        jPanel2.add(jTextField55);

        jTextField57.setEditable(false);
        jTextField57.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField57.setText(student.getCourseAt(4,2));
        jPanel2.add(jTextField57);

        jTextField58.setEditable(false);
        jTextField58.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField58.setText(student.getCourseAt(4,3));
        jPanel2.add(jTextField58);

        jTextField59.setEditable(false);
        jTextField59.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField59.setText(student.getCourseAt(4,4));
        jPanel2.add(jTextField59);

        jTextField60.setEditable(false);
        jTextField60.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField60.setText(student.getCourseAt(4,5));
        jPanel2.add(jTextField60);

        jTextField40.setEditable(false);
        jTextField40.setBackground(new java.awt.Color(173, 112, 96));
        jTextField40.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField40.setForeground(new java.awt.Color(220, 172, 146));
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setText("12.30-13.20");
        jTextField40.setToolTipText("");
        jPanel2.add(jTextField40);

        jTextField61.setEditable(false);
        jTextField61.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField61);

        jTextField62.setEditable(false);
        jTextField62.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField62);

        jTextField63.setEditable(false);
        jTextField63.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField63);

        jTextField64.setEditable(false);
        jTextField64.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField64);

        jTextField65.setEditable(false);
        jTextField65.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField65);

        jTextField41.setEditable(false);
        jTextField41.setBackground(new java.awt.Color(173, 112, 96));
        jTextField41.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField41.setForeground(new java.awt.Color(220, 172, 146));
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("13.30-14.20");
        jTextField41.setToolTipText("");
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField41);

        jTextField66.setEditable(false);
        jTextField66.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField66.setText(student.getCourseAt(5,1));
        jPanel2.add(jTextField66);

        jTextField67.setEditable(false);
        jTextField67.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField67.setText(student.getCourseAt(5,2));
        jPanel2.add(jTextField67);

        jTextField68.setEditable(false);
        jTextField68.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField68.setText(student.getCourseAt(5,3));
        jPanel2.add(jTextField68);

        jTextField69.setEditable(false);
        jTextField69.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField69.setText(student.getCourseAt(5,4));
        jPanel2.add(jTextField69);

        jTextField70.setEditable(false);
        jTextField70.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField70.setText(student.getCourseAt(5,5));
        jPanel2.add(jTextField70);

        jTextField44.setEditable(false);
        jTextField44.setBackground(new java.awt.Color(173, 112, 96));
        jTextField44.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField44.setForeground(new java.awt.Color(220, 172, 146));
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField44.setText("14.30.15.20");
        jTextField44.setToolTipText("");
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField44);

        jTextField71.setEditable(false);
        jTextField71.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField71.setText(student.getCourseAt(6,1));
        jPanel2.add(jTextField71);

        jTextField72.setEditable(false);
        jTextField72.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField72.setText(student.getCourseAt(6,2));
        jPanel2.add(jTextField72);

        jTextField73.setEditable(false);
        jTextField73.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField73.setText(student.getCourseAt(6,3));
        jPanel2.add(jTextField73);

        jTextField74.setEditable(false);
        jTextField74.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField74.setText(student.getCourseAt(6,4));
        jPanel2.add(jTextField74);

        jTextField75.setEditable(false);
        jTextField75.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField75.setText(student.getCourseAt(6,5));
        jPanel2.add(jTextField75);

        jTextField50.setEditable(false);
        jTextField50.setBackground(new java.awt.Color(173, 112, 96));
        jTextField50.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField50.setForeground(new java.awt.Color(220, 172, 146));
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setText("15.30-16.20");
        jTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField50);

        jTextField76.setEditable(false);
        jTextField76.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField76.setText(student.getCourseAt(7,1));
        jPanel2.add(jTextField76);

        jTextField77.setEditable(false);
        jTextField77.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField77.setText(student.getCourseAt(7,2));
        jPanel2.add(jTextField77);

        jTextField78.setEditable(false);
        jTextField78.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField78.setText(student.getCourseAt(7,3));
        jPanel2.add(jTextField78);

        jTextField79.setEditable(false);
        jTextField79.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField79.setText(student.getCourseAt(7,4));
        jPanel2.add(jTextField79);

        jTextField80.setEditable(false);
        jTextField80.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField80ActionPerformed(evt);
            }
        });
        jTextField80.setText(student.getCourseAt(7,5));
        jPanel2.add(jTextField80);

        jTextField81.setEditable(false);
        jTextField81.setBackground(new java.awt.Color(173, 112, 96));
        jTextField81.setFont(new java.awt.Font("PT Sans Caption", 1, 12)); // NOI18N
        jTextField81.setForeground(new java.awt.Color(220, 172, 146));
        jTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField81.setText("16.30-17.20");
        jTextField81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField81ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField81);

        jTextField82.setEditable(false);
        jTextField82.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField82ActionPerformed(evt);
            }
        });
        jTextField82.setText(student.getCourseAt(8,1));
        jPanel2.add(jTextField82);

        jTextField83.setEditable(false);
        jTextField83.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField83.setText(student.getCourseAt(8,2));
        jPanel2.add(jTextField83);

        jTextField84.setEditable(false);
        jTextField84.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField84.setText(student.getCourseAt(8,3));
        jPanel2.add(jTextField84);

        jTextField85.setEditable(false);
        jTextField85.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField85.setText(student.getCourseAt(8,4));
        jPanel2.add(jTextField85);

        jTextField86.setEditable(false);
        jTextField86.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField86.setText(student.getCourseAt(8,5));
        jPanel2.add(jTextField86);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 60, 730, 650);

        jButtonSectionChange.setBackground(new java.awt.Color(220, 172, 146));
        jButtonSectionChange.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jButtonSectionChange.setForeground(new java.awt.Color(172, 112, 96));
        jButtonSectionChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SectionChange/button1.png"))); // NOI18N
        jButtonSectionChange.setText("SINGLE SECTION CHANGE");
        jButtonSectionChange.setToolTipText("");
        jButtonSectionChange.setBorder(null);
        jButtonSectionChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSectionChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSectionChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSectionChangeMouseClicked(evt);
            }
        });
        jButtonSectionChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSectionChangeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSectionChange);
        jButtonSectionChange.setBounds(790, 100, 460, 160);

        jButtonForum.setBackground(new java.awt.Color(220, 172, 146));
        jButtonForum.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jButtonForum.setForeground(new java.awt.Color(172, 112, 96));
        jButtonForum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SectionChange/button1.png"))); // NOI18N
        jButtonForum.setText("FORUM");
        jButtonForum.setToolTipText("");
        jButtonForum.setBorder(null);
        jButtonForum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonForum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonForum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonForumMouseClicked(evt);
            }
        });
        jButtonForum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForumActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonForum);
        jButtonForum.setBounds(790, 520, 460, 160);

        jLabelClose.setFont(new java.awt.Font("Lucida Handwriting", 1, 48)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(1230, 0, 32, 58);

        jButtonMultiChange.setBackground(new java.awt.Color(220, 172, 146));
        jButtonMultiChange.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jButtonMultiChange.setForeground(new java.awt.Color(172, 112, 96));
        jButtonMultiChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SectionChange/button1.png"))); // NOI18N
        jButtonMultiChange.setText("MULTIPLE-CHANGE REQUEST ");
        jButtonMultiChange.setToolTipText("");
        jButtonMultiChange.setBorder(null);
        jButtonMultiChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultiChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMultiChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMultiChangeMouseClicked(evt);
            }
        });
        jButtonMultiChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiChangeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiChange);
        jButtonMultiChange.setBounds(790, 310, 460, 160);

        HomeButton.setBackground(new java.awt.Color(220, 172, 146));
        HomeButton.setForeground(new java.awt.Color(220, 172, 146));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SectionChange/home.png"))); // NOI18N
        HomeButton.setBorder(null);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButton);
        HomeButton.setBounds(1130, 0, 60, 50);

        jLabelMinimize.setFont(new java.awt.Font("Lucida Fax", 1, 48)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize);
        jLabelMinimize.setBounds(1190, 0, 31, 58);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField50ActionPerformed

    private void jTextField56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField56ActionPerformed

    private void jTextField81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField81ActionPerformed

    private void jTextField82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField82ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jButtonSectionChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSectionChangeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSectionChangeMouseClicked

    private void jButtonSectionChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSectionChangeActionPerformed
         /*JFrame singleSection = new JFrame();
         JPanel panel = new JPanel(new GridLayout(10, 1, 10, 5));
         Courses courses = new Courses();
         singleSection.setSize(350,350);
         singleSection.setLocationRelativeTo(null);
         JButton b1 = new JButton("MATH102");
         JButton b2 = new JButton("CS102");
         JButton b3 = new JButton("MATH132");
         JButton b4 = new JButton("ENG102");
         b1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel panel2 = new JPanel();
                JFrame frame2 = new JFrame();
                for(int i = 0; i < 3; i++){
                    JButton buttonsOfFirst = new JButton("" + courses.getCourses().get(i));
                    
                    panel2.add(buttonsOfFirst);
                }
                frame2.add(panel2);
                frame2.setVisible(true);
            }
         });
         b2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel panel2 = new JPanel();
                JFrame frame2 = new JFrame();
                for(int i = 3; i < 6; i++){
                    JButton buttonsOfFirst = new JButton("" + courses.getCourses().get(i));
                    buttonsOfFirst.addActionListener(new ActionListener(){
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            
                        }
                    });
                    panel2.add(buttonsOfFirst);
                }
                frame2.add(panel2);
                frame2.setVisible(true);
            }
         });
         b3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel panel2 = new JPanel();
                JFrame frame2 = new JFrame();
                for(int i = 6; i < 9; i++){
                    JButton buttonsOfFirst = new JButton("" + courses.getCourses().get(i));
                    panel2.add(buttonsOfFirst);
                }
                frame2.add(panel2);
                frame2.setVisible(true);
            }
         });
         b4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel panel2 = new JPanel();
                JFrame frame2 = new JFrame();
                for(int i = 9; i < 12; i++){
                    JButton buttonsOfFirst = new JButton("" + courses.getCourses().get(i));
                    panel2.add(buttonsOfFirst);
                }
                frame2.add(panel2);
                frame2.setVisible(true);
            }
         });
         panel.add(b4);
         panel.add(b3);
         panel.add(b2);
         panel.add(b1);
         panel.setBackground(Color.decode("#DCAC92"));
         singleSection.add(panel);
         singleSection.setVisible(true);*/
         SingleChange singleChange = new SingleChange(this.student, courses);
         singleChange.setLocationRelativeTo(null);
         singleChange.setVisible(true);
    }//GEN-LAST:event_jButtonSectionChangeActionPerformed

    private void jButtonForumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonForumMouseClicked

    private void jButtonForumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForumActionPerformed
        Forum forumPage = new Forum(this.student, courses);
        forumPage.setVisible(true);
        forumPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonForumActionPerformed

    private void jTextField80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField80ActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonMultiChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMultiChangeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiChangeMouseClicked

    private void jButtonMultiChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiChangeActionPerformed
        // TODO add your handling code here:
        MultipleChange multiChange = new MultipleChange(this.student, courses);
        multiChange.setLocationRelativeTo(null);
        multiChange.setVisible(true);
    }//GEN-LAST:event_jButtonMultiChangeActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        SchedulePage sPage = new SchedulePage(this.student, courses);
        sPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton jButtonForum;
    private javax.swing.JButton jButtonMultiChange;
    private javax.swing.JButton jButtonSectionChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    // End of variables declaration//GEN-END:variables
}
