/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SchedulePage;

/**
 *
 * @author cagri
 */
public class SchedulePage extends javax.swing.JFrame {

    /**
     * Creates new form SchedulePage
     */
    public SchedulePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 172, 146));

        jPanel1.setBackground(new java.awt.Color(220, 172, 146));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(173, 112, 96));
        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 112, 96));
        jLabel1.setText("Current Schedule");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 350, 70);

        jPanel2.setBackground(new java.awt.Color(220, 172, 146));
        jPanel2.setLayout(new java.awt.GridLayout(10, 6, 10, 10));

        jTextField20.setBackground(new java.awt.Color(173, 112, 96));
        jTextField20.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(220, 172, 146));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("Hours");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField20);

        jTextField18.setBackground(new java.awt.Color(173, 112, 96));
        jTextField18.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(220, 172, 146));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("Mon");
        jPanel2.add(jTextField18);

        jTextField30.setBackground(new java.awt.Color(173, 112, 96));
        jTextField30.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField30.setForeground(new java.awt.Color(220, 172, 146));
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText("Tue");
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField30);

        jTextField32.setBackground(new java.awt.Color(173, 112, 96));
        jTextField32.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField32.setForeground(new java.awt.Color(220, 172, 146));
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText("Wed");
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField32);

        jTextField33.setBackground(new java.awt.Color(173, 112, 96));
        jTextField33.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField33.setForeground(new java.awt.Color(220, 172, 146));
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("Thurs");
        jPanel2.add(jTextField33);

        jTextField34.setBackground(new java.awt.Color(173, 112, 96));
        jTextField34.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField34.setForeground(new java.awt.Color(220, 172, 146));
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("Fri");
        jPanel2.add(jTextField34);

        jTextField21.setBackground(new java.awt.Color(173, 112, 96));
        jTextField21.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(220, 172, 146));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("8.30-9.20");
        jPanel2.add(jTextField21);

        jTextField35.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField35);

        jTextField36.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField36);

        jTextField56.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField56ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField56);

        jTextField37.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField37);

        jTextField42.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField42);

        jTextField22.setBackground(new java.awt.Color(173, 112, 96));
        jTextField22.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(220, 172, 146));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("9.30-10.20");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField22);

        jTextField43.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField43);

        jTextField45.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField45);

        jTextField46.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField46);

        jTextField47.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField47);

        jTextField48.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField48);

        jTextField38.setBackground(new java.awt.Color(173, 112, 96));
        jTextField38.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField38.setForeground(new java.awt.Color(220, 172, 146));
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("10.30-11.20");
        jTextField38.setToolTipText("");
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField38);

        jTextField49.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField49);

        jTextField51.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField51);

        jTextField52.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField52);

        jTextField53.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField53);

        jTextField54.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField54);

        jTextField39.setBackground(new java.awt.Color(173, 112, 96));
        jTextField39.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField39.setForeground(new java.awt.Color(220, 172, 146));
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("11.30-12.20");
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField39);

        jTextField55.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField55);

        jTextField57.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField57);

        jTextField58.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField58);

        jTextField59.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField59);

        jTextField60.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField60);

        jTextField40.setBackground(new java.awt.Color(173, 112, 96));
        jTextField40.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField40.setForeground(new java.awt.Color(220, 172, 146));
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setText("12.30-13.20");
        jTextField40.setToolTipText("");
        jPanel2.add(jTextField40);

        jTextField61.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField61);

        jTextField62.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField62);

        jTextField63.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField63);

        jTextField64.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField64);

        jTextField65.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField65);

        jTextField41.setBackground(new java.awt.Color(173, 112, 96));
        jTextField41.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField41.setForeground(new java.awt.Color(220, 172, 146));
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("13.30-14.20");
        jTextField41.setToolTipText("");
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField41);

        jTextField66.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField66);

        jTextField67.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField67);

        jTextField68.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField68);

        jTextField69.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField69);

        jTextField70.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField70);

        jTextField44.setBackground(new java.awt.Color(173, 112, 96));
        jTextField44.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField44.setForeground(new java.awt.Color(220, 172, 146));
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField44.setText("14.30.15.20");
        jTextField44.setToolTipText("");
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField44);

        jTextField71.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField71);

        jTextField72.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField72);

        jTextField73.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField73);

        jTextField74.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField74);

        jTextField75.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField75);

        jTextField50.setBackground(new java.awt.Color(173, 112, 96));
        jTextField50.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField50.setForeground(new java.awt.Color(220, 172, 146));
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setText("15.30-16.20");
        jTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField50);

        jTextField76.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField76);

        jTextField77.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField77);

        jTextField78.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField78);

        jTextField79.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField79);

        jTextField80.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField80);

        jTextField81.setBackground(new java.awt.Color(173, 112, 96));
        jTextField81.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        jTextField81.setForeground(new java.awt.Color(220, 172, 146));
        jTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField81.setText("16.30-17.20");
        jTextField81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField81ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField81);

        jTextField82.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField82ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField82);

        jTextField83.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField83);

        jTextField84.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField84);

        jTextField85.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField85);

        jTextField86.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        jTextField86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField86);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 70, 720, 630);

        jButton1.setBackground(new java.awt.Color(220, 172, 146));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SchedulePage/Webp.net-resizeimage.png"))); // NOI18N

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(770, 390, 230, 100);

        jButton2.setBackground(new java.awt.Color(220, 172, 146));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SchedulePage/Webp.net-resizeimage.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(760, 170, 230, 100);

        jButton3.setBackground(new java.awt.Color(220, 172, 146));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SchedulePage/Webp.net-resizeimage.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(760, 280, 230, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField50ActionPerformed

    private void jTextField56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField56ActionPerformed

    private void jTextField81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField81ActionPerformed

    private void jTextField82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField82ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    // End of variables declaration//GEN-END:variables
}
